version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm run export # optional if static export
artifacts:
  files:
    - '**/*'
  base-directory: .next # for SSR use .next-lambda folder if using serverless
